app:
    resource: "@AppBundle/Controller/"
    type:     annotation

user_register:
    path:     /register/
    defaults: { _controller: AppBundle:Register:index }
    methods:  [POST]

user_login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }

about:
    path:     /about
    defaults: { _controller: AppBundle:Home:about }
    methods: [GET]

contact:
    path:     /contact
    defaults: { _controller: AppBundle:Home:contact }
    methods: [GET]

deletePost:
    path:     /del/{postId}
    defaults: { _controller: AppBundle:Posts:deletePost }

home:
    path:     /{username}
    defaults: { _controller: AppBundle:Posts:allPosts }
    methods: [GET]

post:
    path:     /
    defaults: { _controller: AppBundle:Posts:post }
    methods: [POST]

index:
    path:     /
    defaults: { _controller: AppBundle:Posts:allPosts }
    methods: [GET]

logout:
    path: /logout
