app:
    resource: "@AppBundle/Controller/"
    type:     annotation

user_register:
    path:     /register/
    defaults: { _controller: AppBundle:Register:index }
    methods:  [POST]

user_login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }

home:
    path:     /home
    defaults: { _controller: AppBundle:Posts:allPosts }
    methods: [GET]

post:
    path:     /
    defaults: { _controller: AppBundle:Posts:post }
    methods: [POST]

index:
    path:     /
    defaults: { _controller: AppBundle:Posts:allPosts }
    methods: [GET]

logout:
    path: /logout
