AppBundle\Entity\Post:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\PostRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        userId:
            type: integer
            column: user_id
        textPost:
            type: string
            length: 255
        postTime:
            type: time
        postDate:
            type: date
        claps:
            type: integer
    manyToOne:
        user:
            targetEntity: User
            inversedBy: posts
            joinColumn:
                name: user_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
